agents = {
    "Pre-Migration Insights Agents": {
        "description": "These agents focus on comprehensive assessment and foundational understanding before the migration execution phase. Evaluates the current state of source systems and data. Ensures adherence to all relevant regulations and internal policies.",
        "narrative": "Conducts a thorough assessment of legacy core banking systems and other data sources. This includes analysing data volume, complexity, existing data quality issues (e.g., duplicates, inconsistencies, missing values), data types, and system architecture. It identifies critical dependencies, data silos, and potential extraction challenges. Insights are fed to the Orchestrator Agent and Data Ingestion Agent. Reviews, interprets, and codifies compliance requirements (e.g., GDPR, Basel III, CCPA, local banking regulations, internal data governance policies) that govern data handling, privacy, retention, and migration. This critical information, transformed into actionable rules and constraints, is fed to the Orchestrator Agent to guide the entire process and inform other agents (e.g., Data Quality, Mapping & Transformation, Security). Utilizes Retrieval Augmented Generation (RAG) to access and contextualize vast regulatory documentation."
    },
    "Data Ingestion, Pre-Check & ETL Pipeline Agents": {
        "description": "These agents handle the initial collection, preparation, and transformation of data and metadata from various sources. Manages the initial collection and secure transfer of data and metadata. Ensures the accuracy, consistency, and completeness of data. Defines how data from the source maps to the target and performs necessary transformations.",
        "narrative": "Connects to diverse source systems (databases, flat files, APIs) Ingests raw data, applying initial pre-checks for format validity and basic structural integrity. Ensures secure data transfer protocols (e.g., encrypted channels). Takes ingested data and applies a comprehensive set of cleansing rules, informed by insights from the Identifies and rectifies data quality issues (e.g., duplicates, inconsistencies, missing values, incorrect formats, outliers). Generates synthetic, statistically representative test data for downstream agents, to aid in testing transformation logic without using sensitive production data. Receives cleaned data and metadata. Utilizes machine learning to learn optimal data mappings between disparate source and target schemas. Creates and executes complex transformation logic (e.g., aggregation, normalization, data type conversion, value lookups) to convert data from the source format to the target format, strictly adhering to rules provided. Flags ambiguous mappings or transformation challenges for review by the Human-in-the-Loop Management Agent, providing context and potential resolutions."
    },
    "Migration Execution & Oversight Agents": {
        "description": "These agents manage the actual data transfer, monitoring, and compliance enforcement. Continuously monitors and enforces compliance throughout the migration lifecycle. Orchestrates the actual data transfer and oversees its progress in real-time. Provides a holistic and proactive security posture across all migration phases.",
        "narrative": "Receives transformation logic and data definitions and actively ensures adherence to regulatory requirements and internal policy rules previously codified. Integrates directly with to log every data operation, transformation, access, and decision made by agents, ensuring an immutable audit trail. Proactively identifies potential compliance breaches or deviations during execution and alerts the Orchestrator Agent. Interprets evolving regulations in real-time, providing critical, updated input."
    },
    "Post-Migration Verification & Management Agents": {
        "description": "These agents ensure data integrity post-migration and provide comprehensive reporting and continuous improvement. Verifies the integrity and completeness of migrated data. Provides comprehensive insights and oversight of the entire migration process.",
        "narrative": "Verifies the integrity and completeness of migrated data. Provides comprehensive insights and oversight of the entire migration process."
    },
    "Cross-Cutting & Support Agents": {
        "description": "These agents provide overarching capabilities essential for the entire Agentic AI system. Ensures business continuity and data recoverability in case of unforeseen failures. Ensures continuous improvement and optimization of the entire Agentic AI system. Manages and optimizes resource utilization and projected costs throughout the migration.",
        "narrative": "Facilitates seamless collaboration between human experts and AI agents. PEnsures continuous improvement and optimization of the entire Agentic AI system."
    }
}
